import type { Metadata } from "next";
import { routing } from "@/i18n/routing";

/**
 * Absolute origin of the production site. Override per environment (preview
 * deployments, staging) so canonical URLs and the sitemap never point at prod.
 */
export const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL?.trim().replace(/\/$/, "") ||
  "https://themindnexus.com";

export const SITE_NAME = "Mind Nexus";

export const SITE_TITLE =
  "Mind Nexus — Resilience and Mental Health for Stronger Workplaces";

export const SITE_DESCRIPTION =
  "Mind Nexus is a psychological consulting company strengthening resilience and mental health at individual, team, and organizational levels. Resilient people. Strong organizations.";

export const CONTACT_EMAIL = "info@themindnexus.com";
export const CONTACT_PHONE = "+383 45 116 162";

/** Generated by app/opengraph-image.tsx. */
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: SITE_TITLE,
};

/**
 * Routes that should appear in the sitemap, ordered by importance. The
 * testimonials placeholder is left out (and marked noindex) until it has real
 * content — thin pages dilute the rest of the site in search.
 */
export const SITEMAP_ROUTES = [
  { path: "/", priority: 1 },
  { path: "/services", priority: 0.9 },
  { path: "/our-approach", priority: 0.9 },
  { path: "/team", priority: 0.8 },
  { path: "/blog", priority: 0.7 },
  { path: "/contact", priority: 0.8 },
  { path: "/terms", priority: 0.2 },
] as const;

/**
 * Builds a page's metadata with a canonical URL and matching Open Graph and
 * Twitter cards, so every route is self-describing when shared or crawled.
 */
export function pageMetadata({
  title,
  description,
  path,
  locale = routing.defaultLocale,
  noindex = false,
}: {
  title: string;
  description: string;
  path: string;
  locale?: string;
  /** Set while a page is still a placeholder, so it stays out of search. */
  noindex?: boolean;
}): Metadata {
  const localizedPath = `/${locale}${path === "/" ? "" : path}`;
  return {
    title,
    description,
    alternates: {
      canonical: localizedPath,
      languages: {
        en: `/en${path === "/" ? "" : path}`,
        sq: `/sq${path === "/" ? "" : path}`,
      },
    },
    robots: noindex ? { index: false, follow: true } : undefined,
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      title: `${title} — ${SITE_NAME}`,
      description,
      url: localizedPath,
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: `${title} — ${SITE_NAME}`,
      description,
      images: [OG_IMAGE.url],
    },
  };
}
